#!/usr/bin/env ruby

require 'optparse'
require 'webrick'
require "#{__dir__}/lib/plot.rb"
require 'erb'

def usage
  puts 'see --help'
  exit 0
end

# args
opts = ARGV.getopts('', 'log:', 'port:')
port = opts['port'] || 20_080
log = opts['log']

# args validation
usage unless log

# server
srv = WEBrick::HTTPServer.new(BindAddress: '0.0.0.0', Port: port)

srv.mount_proc('/') do |req, res|
  erb = ERB.new File.open("#{__dir__}/templates/index.html").read
  res.body = erb.result(binding)
end

srv.mount_proc('/log/epoch') do |req, res|
  xrange = req.query['xrange']
  yrange = req.query['yrange']
  png = plot(log, 'epoch', xrange, yrange)
  res.body = File.open(png, 'rb').read
end

srv.mount_proc('/log/iteration') do |req, res|
  xrange = req.query['xrange']
  yrange = req.query['yrange']
  png = plot(log, 'iteration', xrange, yrange)
  res.body = File.open(png, 'rb').read
end

trap('INT') { srv.shutdown }
srv.start
