#!/usr/bin/env ruby

require 'optparse'
require 'webrick'
require "#{__dir__}/lib/plot.rb"
require 'erb'

def usage
    puts "see --help"
    exit 0
end

# args
opts = ARGV.getopts('', 'log:', 'port:')
port = opts['port'] || 20080
log = opts['log']

# args validation
usage if !log

# server
srv = WEBrick::HTTPServer.new({ :BindAddress => '0.0.0.0', :Port => port})

srv.mount_proc('/') {|req, res|
    erb = ERB.new File.open("#{__dir__}/templates/index.html").read
    res.body = erb.result(binding)
}

srv.mount_proc('/log/epoch/main') {|req, res|
    png = plot(log, 'epoch', 'main')
    res.body = File.open(png, 'rb').read()
}
srv.mount_proc('/log/epoch/validation') {|req, res|
    png = plot(log, 'epoch', 'validation')
    res.body = File.open(png, 'rb').read()
}
srv.mount_proc('/log/iteration/main') {|req, res|
    png = plot(log, 'iteration', 'main')
    res.body = File.open(png, 'rb').read()
}
srv.mount_proc('/log/iteration/validation') {|req, res|
    png = plot(log, 'iteration', 'validation')
    res.body = File.open(png, 'rb').read()
}
trap("INT"){ srv.shutdown }
srv.start
